name: test_env_cmip6_preprocessing
channels:
  - conda-forge
  - numba #TODO: Remove this once numba is an optional dependency on xarrayutils (https://github.com/jbusecke/xarrayutils/issues/138) 
dependencies:
  - xarray>=0.17.0
  - pandas
  - netcdf4
  - scipy
  - xgcm<0.7.0 #Revert this after fixing the extrapolate option
  - cftime
  - regionmask
  - cartopy
  - xesmf
  - xarrayutils #TODO remove when the new xarray polyfit is implemented
  - pint
  - cf_xarray>=0.6.0
  - pint-xarray>=0.2.1
  - pytest-cov
  - pytest-xdist
  - codecov
