name: test_env_cmip6_preprocessing
channels:
  - conda-forge
dependencies:
  - xarray>=0.17.0
  - pandas
  - netcdf4
  - scipy
  - xgcm<0.7.0
  - cftime
  - regionmask
  - cartopy
  - xesmf
  - xarrayutils
  - pint
  - cf_xarray>=0.6.0
  - pint-xarray>=0.2.1
  - pytest-cov
  - pytest-xdist
  - codecov
